name: load-balancer-demo

services:
  app1:
    build:
      context: .
    environment:
      - APP_NAME=App1
    ports:
      - "8081:8080"

  app2:
    build:
      context: .
    environment:
      - APP_NAME=App2
    ports:
      - "8082:8080"

  app3:
    build:
      context: .
    environment:
      - APP_NAME=App3
    ports:
      - "8083:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount the SSL folder into the container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # This is where we reference your custom nginx.conf
    ports:
      - "80:80"
      - "443:443"  # If using SSL, expose port 443 for HTTPS
    depends_on:
      - app1
      - app2
      - app3
